/**
 * ImgBB image upload utility.
 *
 * Uses the ImgBB API v1 for anonymous image hosting.
 * https://api.imgbb.com
 *
 * API key: reads from VITE_IMGBB_API_KEY env var at build time,
 * falling back to a hardcoded default.
 */

const IMGBB_API_KEY =
  (import.meta as any).env?.VITE_IMGBB_API_KEY || "f020706c7fb3cb70ebb8290c29745ca5";
// ^^^ Replace YOUR_IMGBB_KEY_HERE with your key from https://api.imgbb.com
//     or set VITE_IMGBB_API_KEY in the environment / .env file.

const API = "https://api.imgbb.com/1/upload";

export interface ImgbbResult {
  id: string;
  url: string;           // full-size image URL
  display_url: string;   // display page
  thumb_url: string;     // thumbnail
  delete_url: string;    // deletion link
  width: number;
  height: number;
}

/**
 * Upload a single base64-encoded PNG image to ImgBB.
 */
export async function uploadImage(
  base64Data: string,
  name?: string,
): Promise<ImgbbResult> {
  const body = new FormData();
  body.append("key", IMGBB_API_KEY);
  body.append("image", base64Data);
  if (name) body.append("name", name);

  const resp = await fetch(API, { method: "POST", body });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`ImgBB upload failed (${resp.status}): ${text}`);
  }

  const json = await resp.json();
  if (!json.success) {
    throw new Error(`ImgBB error: ${json.error?.message || JSON.stringify(json)}`);
  }

  const d = json.data;
  return {
    id: d.id,
    url: d.url || d.image?.url,
    display_url: d.url_viewer || d.display_url,
    thumb_url: d.thumb?.url || d.url,
    delete_url: d.delete_url || "",
    width: d.width,
    height: d.height,
  };
}

/**
 * Upload all plots. Returns per-image results.
 * (ImgBB doesn't have albums like Imgur, so we just upload individually
 * and return all links together.)
 */
export async function uploadAllPlots(
  plots: Record<string, string>,
  labels: Record<string, string>,
  titlePrefix: string,
): Promise<{ images: { name: string; label: string; url: string; display_url: string }[] }> {
  const images: { name: string; label: string; url: string; display_url: string }[] = [];

  for (const [name, b64] of Object.entries(plots)) {
    if (!b64) continue;
    const label = labels[name] || name;
    const result = await uploadImage(b64, `${titlePrefix}_${name}`);
    images.push({
      name,
      label,
      url: result.url,
      display_url: result.display_url,
    });
  }

  return { images };
}

/**
 * Format helpers for forum embedding.
 */
export function markdownEmbed(url: string, alt: string): string {
  return `![${alt}](${url})`;
}

export function bbcodeEmbed(url: string): string {
  return `[img]${url}[/img]`;
}

export function htmlEmbed(url: string, alt: string): string {
  return `<img src="${url}" alt="${alt}" />`;
}

/**
 * Generate a ready-to-paste forum post (BBCode) with all plots embedded.
 */
export function forumPost(
  images: { label: string; url: string }[],
  ticId?: number | null,
  sector?: number | null,
): string {
  const header = ticId
    ? `[b]Vetstar Vetting Report — TIC ${ticId}${sector ? ` Sector ${sector}` : ""}[/b]\n`
    : "[b]Vetstar Vetting Report[/b]\n";
  const lines = images.map(
    (img) => `[b]${img.label}[/b]\n${bbcodeEmbed(img.url)}`,
  );
  const credit = `\n\n[i]Generated by [url=https://vetstar.onrender.com]Vetstar: TESS Vetting Studio[/url][/i]`;
  return header + lines.join("\n\n") + credit;
}
